version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 576165291816.dkr.ecr.eu-cental-1.amazonaws.com
  build:
    commands:
      - echo Starting build at `date`
      - echo Building the Docker image...          
      - docker build --tag 576165291816.dkr.ecr.eu-cental-1.amazonaws.com/backend:latest .
  post_build:
    commands:
      - echo Completed build at `date`
      - echo Pushing the Docker image...
      - docker push 576165291816.dkr.ecr.eu-cental-1.amazonaws.com/backend:latest
