apiVersion: v1
kind: Service
metadata:
  name: coworking
spec:
  type: LoadBalancer
  selector:
    service: coworking
  ports:
  - name: "5153"
    protocol: TCP
    port: 5153
    targetPort: 5153
    nodePort: 30008 # Port on the node to expose to load balancer. Security group of node must accept traffic on that port from load balancer.